import classnames from 'classnames';
import styles from './userInfo.module.css';

type UserInfoProps = {
  className?: string;
};

export const UserInfo = ({ className }: UserInfoProps) => {
  return <div className={classnames(styles.userInfo, className)}>This is autogenerated userInfo!</div>;
};
