import classnames from 'classnames';
import styles from './component.module.scss';

type ComponentProps = {
  className?: string;
};

export const Component = ({ className }: ComponentProps) => {
  return <div className={classnames(styles.component, className)}>This is autogenerated component!</div>;
};
